// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkOJ92E4dI2R1npqTiTQckAFk_6g0uuEk',
    appId: '1:74556218954:web:d89248e40121d96b3550b3',
    messagingSenderId: '74556218954',
    projectId: 'harvest-587ba',
    authDomain: 'harvest-587ba.firebaseapp.com',
    storageBucket: 'harvest-587ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCTlPQnlrhWlD53muUXa6sb7sG3QECT14',
    appId: '1:74556218954:android:a9aab8f50a62c73d3550b3',
    messagingSenderId: '74556218954',
    projectId: 'harvest-587ba',
    storageBucket: 'harvest-587ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2i26P8OAa9tpDB9ukvByWQE_Kvu2yE5Y',
    appId: '1:74556218954:ios:52b95acbbc469b5c3550b3',
    messagingSenderId: '74556218954',
    projectId: 'harvest-587ba',
    storageBucket: 'harvest-587ba.firebasestorage.app',
    iosBundleId: 'com.example.harvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2i26P8OAa9tpDB9ukvByWQE_Kvu2yE5Y',
    appId: '1:74556218954:ios:52b95acbbc469b5c3550b3',
    messagingSenderId: '74556218954',
    projectId: 'harvest-587ba',
    storageBucket: 'harvest-587ba.firebasestorage.app',
    iosBundleId: 'com.example.harvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkOJ92E4dI2R1npqTiTQckAFk_6g0uuEk',
    appId: '1:74556218954:web:ce24c302769d0f713550b3',
    messagingSenderId: '74556218954',
    projectId: 'harvest-587ba',
    authDomain: 'harvest-587ba.firebaseapp.com',
    storageBucket: 'harvest-587ba.firebasestorage.app',
  );
}
